services:
  # Redis on Render (used for caching Audius nodes)
  - type: redis
    name: sonexa-redis
    plan: free
    ipAllowList: []

  # Backend Spring Boot Service
  - type: web
    name: sonexa-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        sync: false # Render will prompt you to enter your TiDB Host
      - key: DB_PORT
        value: "4000" # TiDB default port is 4000
      - key: DB_NAME
        sync: false # Render will prompt you to enter your TiDB Database name
      - key: DB_USER
        sync: false # Render will prompt you to enter your TiDB User
      - key: DB_PASS
        sync: false # Render will prompt you to enter your TiDB Password
      - key: REDIS_HOST
        fromRedis:
          name: sonexa-redis
          property: host
      - key: REDIS_PORT
        fromRedis:
          name: sonexa-redis
          property: port
      - key: JWT_SECRET
        generateValue: true

  # Frontend static service served on Render
  - type: static
    name: sonexa-frontend
    buildCommand: npm run build
    publishDir: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          name: sonexa-backend
          value: url
